ALTER TABLE Car ADD color TEXT;

ALTER TABLE Car ADD bolor TEXT NOT NULL DEFAULT 'white';

ALTER TABLE Car
    ADD COLUMN aolor TEXT,
    ADD COLUMN holor TEXT,
    ADD COLUMN dolor TEXT;

SELECT * FROM Car;
